### ISSUE TITLE
Windows incompatability

### ISSUE THREAD

**Issue by vpetersson** [YippieMove/yippiemove-cli#6]
It appears as the unicode support is broken in Windows. 

```
C:\wireload-yippiemove-cli-f305e04>python yippiemove.py wizard

================================================================
  Step 1: Where are we moving from?
================================================================

[...]

  125) U of Notre Dame
  126) U of San Francisco
  127) U of Southern Florida
  128) U of Virginia (McIntire)
Traceback (most recent call last):
  File "yippiemove.py", line 988, in <module>
    main()
  File "yippiemove.py", line 966, in main
    result = func(**args)
  File "yippiemove.py", line 678, in wizard
    source_email_account = get_and_verify_email_account(new_move_job, "source")
  File "yippiemove.py", line 537, in get_and_verify_email_account
    account = get_email_account_from_user(providers)
  File "yippiemove.py", line 501, in get_email_account_from_user
    print "  %2d) %s" % (i + 1, provider['name'])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map) UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 21: character maps to <undefined>
```

**Comment by aljungberg** [comment]
Is the Windows command line unicode compatible? Either way it looks like that print statement should read `print u"  %2d..."`.
